# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# -- GENERATED SEED DATA --

# with data as (
#   select top 100 *
#   from [STARS_PROD].[dbo].tblInstitution
#   order by newid()
# )
# select
# 'Institution.create( ' +
#     'nci_identifier: "' + coalesce(NCIID, '') + '", ' +
#     'name: "' + Name + '", ' +
#     'stat_group: "' + coalesce(StatisticalGroup, '') + '", ' +
#     'coop_group: "' + coalesce(InstitutionCooperativeGroup, '') + '", ' +
#     'coop_group_inst_id: "' + coalesce(GroupInstitutionID, '') + '", ' +
#     'active: ' + case when [IsActive] = 1 then 'true' else 'false' end +
#     ')' as Line
# from data;
Institution.delete_all
Institution.create( nci_identifier: "", name: "University of Chicago", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "GA040", name: "Phoebe Putney Memorial Hospital", stat_group: "SWOG", coop_group: "ALLIANCE", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "PA086", name: "Fox Chase Cancer Center", stat_group: "SWOG", coop_group: "ACOSOG", coop_group_inst_id: "14235", active: true)
Institution.create( nci_identifier: "NC031", name: "Mission Hospitals Inc", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "14945", active: true)
Institution.create( nci_identifier: "MN002", name: "United Hospital", stat_group: "SWOG", coop_group: "MPC", coop_group_inst_id: "14034", active: true)
Institution.create( nci_identifier: "OH066", name: "Firelands Regional Medical Center", stat_group: "SWOG", coop_group: "RTOG", coop_group_inst_id: "16536", active: true)
Institution.create( nci_identifier: "MO150", name: "Heartland Cancer Research CCOP", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "16111", active: true)
Institution.create( nci_identifier: "OH292", name: "University Hospitals/Ireland Cancer Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "11795", active: true)
Institution.create( nci_identifier: "CA252", name: "Kaiser Permanente", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "12365", active: true)
Institution.create( nci_identifier: "", name: "Michigan State University Clincal Center", stat_group: "SWOG", coop_group: "", coop_group_inst_id: "18925", active: true)
Institution.create( nci_identifier: "RI012", name: "Women and Infants Hospital", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "14980", active: true)
Institution.create( nci_identifier: "WI027", name: "Saint Vincent Hospital", stat_group: "SWOG", coop_group: "ACOSOG", coop_group_inst_id: "15280", active: true)
Institution.create( nci_identifier: "MI116", name: "Mecosta County Medical Center", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "16467", active: true)
Institution.create( nci_identifier: "MN013", name: "Hennepin County Medical Center", stat_group: "SWOG", coop_group: "MPC", coop_group_inst_id: "15218", active: true)
Institution.create( nci_identifier: "NY035", name: "Staten Island University Hospital", stat_group: "SWOG", coop_group: "NRG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "LA040", name: "Ochsner Clinic CCOP", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "12318", active: true)
Institution.create( nci_identifier: "MD053", name: "Associates In Oncology Hematology PC - Rockville", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "", active: false)
Institution.create( nci_identifier: "NY074", name: "Brookdale Hospital Medical Center", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "13059", active: true)
Institution.create( nci_identifier: "IL188", name: "Galesburg Clinic", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "15999", active: true)
Institution.create( nci_identifier: "", name: "Geisinger Medical Center", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "IA004", name: "Iowa Methodist Medical Center", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "11813", active: true)
Institution.create( nci_identifier: "", name: "British Columbia Children's Hospital", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "MN019", name: "Mercy Hospital", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "12417", active: true)
Institution.create( nci_identifier: "WI112", name: "Duluth Clinic Ashland", stat_group: "SWOG", coop_group: "NCCTG", coop_group_inst_id: "16254", active: true)
Institution.create( nci_identifier: "LA035", name: "Mary Bird Perkins Cancer Center", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "15908", active: true)
Institution.create( nci_identifier: "NV017", name: "University Medical Center of Southern Nevada", stat_group: "SWOG", coop_group: "CALGB", coop_group_inst_id: "11963", active: true)
Institution.create( nci_identifier: "NJ048", name: "Saint Peter's University Hospital", stat_group: "SWOG", coop_group: "RTOG", coop_group_inst_id: "16236", active: true)
Institution.create( nci_identifier: "MN041", name: "Saint John's Hospital - Healtheast", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "12539", active: true)
Institution.create( nci_identifier: "CA621", name: "Cancer Care Associates", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13866", active: true)
Institution.create( nci_identifier: "MO023", name: "Southeast Missouri Hospital", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "16030", active: true)
Institution.create( nci_identifier: "", name: "Marshfield Clinic", stat_group: "CTEP", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "", name: "New York Medical College", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "KY099", name: "Jewish Hospital Medical Center", stat_group: "SWOG", coop_group: "NRG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "", name: "University of Wisconsin Hospital and Clinics", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "CA136", name: "University of California at San Francisco", stat_group: "SWOG", coop_group: "CALGB", coop_group_inst_id: "12060", active: true)
Institution.create( nci_identifier: "MI117", name: "Metro Health Hospital", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "16454", active: true)
Institution.create( nci_identifier: "CA249", name: "Moores University of California San Diego Cancer C", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "15751", active: true)
Institution.create( nci_identifier: "PA124", name: "Paoli Memorial Hospital", stat_group: "SWOG", coop_group: "ECOG-ACRIN", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "MD047", name: "Union Hospital of Cecil County", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "14124", active: true)
Institution.create( nci_identifier: "FL086", name: "Florida Hospital", stat_group: "SWOG", coop_group: "ALLIANCE", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "", name: "King Faisal Specialist Hospital & Research Centre", stat_group: "SWOG", coop_group: "", coop_group_inst_id: "13697", active: true)
Institution.create( nci_identifier: "", name: "University of Puerto Rico", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "MN119", name: "Lakeview Hospital", stat_group: "SWOG", coop_group: "NRG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NJ110", name: "Somerset Medical Center", stat_group: "SWOG", coop_group: "NRG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "GA045", name: "John B Amos Cancer Center", stat_group: "SWOG", coop_group: "RTOG", coop_group_inst_id: "15239", active: true)
Institution.create( nci_identifier: "TN116", name: "Vanderbilt-Ingram Cancer Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13934", active: true)
Institution.create( nci_identifier: "NY155", name: "VA Western New York Healthcare System", stat_group: "SWOG", coop_group: "CALGB", coop_group_inst_id: "12259", active: true)
Institution.create( nci_identifier: "OH014", name: "Saint Vincent Mercy Medical Center", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "12690", active: true)
Institution.create( nci_identifier: "NY093", name: "Winthrop University Hospital", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "12465", active: true)
Institution.create( nci_identifier: "KY002", name: "University of Louisville", stat_group: "SWOG", coop_group: "SWOG", coop_group_inst_id: "11293", active: true)
Institution.create( nci_identifier: "SD011", name: "CCOP Sioux Community Cancer Consortium", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "15318", active: true)
Institution.create( nci_identifier: "NE020", name: "Saint Elizabeth Regional Medical Center", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "14657", active: true)
Institution.create( nci_identifier: "NY158", name: "Roswell Park Cancer Institute", stat_group: "SWOG", coop_group: "NCCTG", coop_group_inst_id: "15012", active: true)
Institution.create( nci_identifier: "ND005", name: "Roger Maris Cancer Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13532", active: true)
Institution.create( nci_identifier: "TN037", name: "Meharry Medical College", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "13845", active: true)
Institution.create( nci_identifier: "CT008", name: "Saint Francis Hospital and Medical Center", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "13185", active: true)
Institution.create( nci_identifier: "CA192", name: "Kaiser Permanente - Sacramento", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13228", active: true)
Institution.create( nci_identifier: "VA084", name: "Virginia Oncology Associates", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13361", active: true)
Institution.create( nci_identifier: "", name: "Istituto Nazionale Tumori ", stat_group: "SARC", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "SC045", name: "Greenville Memorial Hospital", stat_group: "SWOG", coop_group: "CALGB", coop_group_inst_id: "16340", active: true)
Institution.create( nci_identifier: "WI004", name: "Zablocki Veterans Administration Medical Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "12557", active: true)
Institution.create( nci_identifier: "", name: "Nationwide Children's Hospital", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NY141", name: "State University of New York Upstate Medical Unive", stat_group: "SWOG", coop_group: "ACOSOG", coop_group_inst_id: "13914", active: true)
Institution.create( nci_identifier: "", name: "University of Kentucky", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NC043", name: "New Hanover Regional Medical Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "11756", active: true)
Institution.create( nci_identifier: "IL069", name: "Saint Mary's Hospital", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "12528", active: true)
Institution.create( nci_identifier: "43030", name: "Seoul National University Bundang Hopsital", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "IA072", name: "Medical Oncology & Hematology Associates-Des Moine", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "12011", active: true)
Institution.create( nci_identifier: "", name: "AML Biology Reference", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NJ202", name: "Sparta Cancer Center", stat_group: "SWOG", coop_group: "NRG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "", name: "Providence Memorial Hospital - El Paso", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NE034", name: "Alegent Health Community Memorial Hospital", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "14653", active: true)
Institution.create( nci_identifier: "IL232", name: "Community Cancer Center Foundation", stat_group: "SWOG", coop_group: "CALGB", coop_group_inst_id: "16394", active: true)
Institution.create( nci_identifier: "ID011", name: "Saint Alphonsus Regional Medical Center", stat_group: "SWOG", coop_group: "SWOG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "OH099", name: "The Toledo Hospital", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "13735", active: true)
Institution.create( nci_identifier: "ND027", name: "Dakota Clinic Cancer Institute", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "12771", active: true)
Institution.create( nci_identifier: "PA243", name: "Ephrata Cancer Center", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "13787", active: true)
Institution.create( nci_identifier: "CT038", name: "Eastern Connecticut Hematology and Oncology Associ", stat_group: "SWOG", coop_group: "NCICIRB", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "IN062", name: "Howard Regional Healthcare System", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "13421", active: true)
Institution.create( nci_identifier: "WA139", name: "Cancer Research and Biostatistics", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "13884", active: true)
Institution.create( nci_identifier: "SD006", name: "Rapid City Regional Hospital", stat_group: "SWOG", coop_group: "NCCTG", coop_group_inst_id: "13475", active: true)
Institution.create( nci_identifier: "OH291", name: "Saint Joseph Cancer ", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "11624", active: true)
Institution.create( nci_identifier: "CA011", name: "University of Southern California", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "15611", active: true)
Institution.create( nci_identifier: "11203", name: "Toronto East General Hospital", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "13032", active: true)
Institution.create( nci_identifier: "CO062", name: "Poudre Valley Radiation Oncology", stat_group: "SWOG", coop_group: "NCCTG", coop_group_inst_id: "14724", active: true)
Institution.create( nci_identifier: "PA138", name: "Geisinger Wyoming Valley", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "13150", active: true)
Institution.create( nci_identifier: "", name: "San Jorge Children's Hospital", stat_group: "NWTS – unresolved", coop_group: "", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "SCCC", name: "Southeast Clinical Onc Research Consortium NCORP", stat_group: "SWOG", coop_group: "", coop_group_inst_id: "11108", active: true)
Institution.create( nci_identifier: "NH015", name: "New Hampshire Oncology Hematology Associates", stat_group: "SWOG", coop_group: "ALLIANCE", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "NV011", name: "Saint Mary's Regional Medical Center", stat_group: "SWOG", coop_group: "SWOG", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "IA034", name: "Siouxland Regional Cancer Center", stat_group: "SWOG", coop_group: "NCICIRB", coop_group_inst_id: "", active: true)
Institution.create( nci_identifier: "OH221", name: "Upper Valley Medical Center", stat_group: "SWOG", coop_group: "NSABP", coop_group_inst_id: "16501", active: true)
Institution.create( nci_identifier: "CT009", name: "Hartford Hospital", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "13574", active: true)
Institution.create( nci_identifier: "OH151", name: "Saint Luke's Hospital", stat_group: "SWOG", coop_group: "ECOG", coop_group_inst_id: "12393", active: true)
Institution.create( nci_identifier: "WA113", name: "Harrison Bremerton Hematology & Oncology", stat_group: "SWOG", coop_group: "SWOG", coop_group_inst_id: "11548", active: true)
Institution.create( nci_identifier: "IL082", name: "OSF Saint Francis Medical Center", stat_group: "SWOG", coop_group: "NCCTG", coop_group_inst_id: "14518", active: true)
Institution.create( nci_identifier: "IL031", name: "Rush - Copley Medical Center", stat_group: "SWOG", coop_group: "CTEP", coop_group_inst_id: "12388", active: true)
Institution.create( nci_identifier: "NJ040", name: "Capital Health System", stat_group: "SWOG", coop_group: "RTOG", coop_group_inst_id: "16482", active: true)
Institution.create( nci_identifier: "KY003", name: "Jewish Hospital", stat_group: "SWOG", coop_group: "CTSU", coop_group_inst_id: "12548", active: true)
Institution.create( nci_identifier: "NJ019", name: "Valley Hospital", stat_group: "SWOG", coop_group: "GOG", coop_group_inst_id: "15729", active: true)

SiteType.delete_all
SiteType.create( name: 'Collection Site', description: 'Location where biospecimens are collected')
SiteType.create( name: 'Laboratory', description: 'Location where biospecimens are processed')
SiteType.create( name: 'Repository', description: 'Location where biospecimens are stored')
SiteType.create( name: 'Room', description: 'Location where biospecimens are stored')
SiteType.create( name: 'Pathologist', description: 'Location where biospecimens are Reviewed')
SiteType.create( name: 'not specified', description: 'Location is not specified')
SiteType.create( name: 'Path Center', description: 'BPC Path')